#!/usr/bin/env bash
# Build the release `jclaw` binary and install a global launcher into
# ~/.local/bin, so `cd <project> && jclaw` opens the vendored TUI there.
#
# Idempotent: re-run after rebuilding to refresh the launcher.
#
# Prereqs:
#   - Rust toolchain (cargo)
#   - Bun at ~/.bun/bin/bun  (https://bun.sh)
#   - `bun install` already run in tui/  (vendored TUI dependencies)
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN="$REPO/rust/target/release/jclaw"
BINDIR="${JCLAW_BINDIR:-$HOME/.local/bin}"
LAUNCHER="$BINDIR/jclaw"

echo "Building release jclaw…"
( cd "$REPO/rust" && cargo build --release --bin jclaw )

mkdir -p "$BINDIR"
# The launcher clears inherited provider/model env vars so jclaw uses its own
# saved config rather than a global ANTHROPIC_MODEL / stray API keys from the
# shell. It then execs the release binary; bare `jclaw` opens the TUI in the
# current directory.
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# jclaw — launch the jclaw TUI from anywhere, in the current directory.
# Generated by scripts/install-jclaw.sh; edit that script, not this file.
unset ANTHROPIC_MODEL ANTHROPIC_DEFAULT_MODEL CLAW_MODEL
unset OPENAI_API_KEY OPENAI_BASE_URL ANTHROPIC_API_KEY ANTHROPIC_AUTH_TOKEN ANTHROPIC_BASE_URL
exec "$BIN" "\$@"
EOF
chmod +x "$LAUNCHER"

echo "Installed launcher: $LAUNCHER -> $BIN"

# Post-install sanity notes (warn, don't fail).
case ":$PATH:" in
  *":$BINDIR:"*) : ;;
  *) echo "NOTE: $BINDIR is not on your PATH. Add:  export PATH=\"$BINDIR:\$PATH\"" ;;
esac
[ -x "$HOME/.bun/bin/bun" ] || echo "NOTE: Bun not found at ~/.bun/bin/bun — install from https://bun.sh"
[ -d "$REPO/tui/node_modules" ] || echo "NOTE: run 'cd $REPO/tui && bun install' before first launch."

echo "Done.  Run:  cd <project> && jclaw"
